### ISSUE TITLE
JPeek command line from README doesn't work

### ISSUE THREAD

**Issue by rexim** [yegor256/jpeek#158]
Command line: https://github.com/yegor256/jpeek/tree/bcab016ee68717091fd0b8345e78f507cade036c#how-to-use

### Steps to reproduce

- Full build `$ mvn clean install -Pqulice`
- `$ java -jar ./target/jpeek-jar-with-dependencies.jar --sources=src/ --target=./jpeek-target/`

### Observed

Exception:

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--sources=.' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at org.jpeek.Main.main(Main.java:97)
```

### Expected

Analysis process of some kind that leads to generated reports in `jpeek-target` folder.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rexim fixed in e42c4de thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#158` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#158](https://github.com/yegor256/jpeek/issues/158) was not in scope
