### ISSUE TITLE
NPE at TkReport

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#191]
The URL is http://i.jpeek.org/org.hsqldb/hsqldb/index.html. This is what I see:

```
java.lang.IllegalStateException: [GET http://i.jpeek.org/org.hsqldb/hsqldb/index.html] failed in 1ms: null
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.jpeek.web.TkReport.act(TkReport.java:78)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:209)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
	... 13 more
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.2`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@0crat quality is acceptable

**Comment by 0crat** [comment]
> @0crat quality is acceptable ([here](https://github.com/yegor256/jpeek/issues/191#issuecomment-366340010))

@ypshenychka Can't understand "quality", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/191#issuecomment-366422429))

@ypshenychka Job `gh:yegor256/jpeek#191` is not assigned, can't get start time

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+30](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job [#191](https://github.com/yegor256/jpeek/issues/191) is now out of scope
