### ISSUE TITLE
jpeek fails to run

### ISSUE THREAD

**Issue by wolkenschieber** [yegor256/jpeek#20]
I fail to run jpeek. I end up in exceptions when runnnig the maven repository jar and compiled sources.

When running the repository jar, given in the readme, some class is reported missing:
```
$ java -jar ~/tools/jpeek/jpeek-0.1-jar-with-dependencies.jar . /tmp/jpeek
Exception in thread "main" java.io.IOException: java.io.UncheckedIOException: java.io.IOException: java.lang.IllegalStateException: javassist.NotFoundException: com.company.releng.tools.deploy.locations.DeployLocations
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
        at org.jpeek.App.analyze(App.java:96)
        at org.jpeek.Main.main(Main.java:61)
Caused by: java.io.UncheckedIOException: java.io.IOException: java.lang.IllegalStateException: javassist.NotFoundException: com.company.releng.tools.deploy.locations.DeployLocations
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
        at org.cactoos.iterator.Mapped.next(Mapped.java:70)
        at org.jpeek.metrics.cohesion.CAMC.metrics(CAMC.java:118)
        at org.jpeek.metrics.cohesion.CAMC.xembly(CAMC.java:91)
        at org.jpeek.App.lambda$analyze$0(App.java:85)
        at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
        at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
        at org.cactoos.scalar.And.lambda$null$0(And.java:101)
        at org.cactoos.scalar.And.value(And.java:127)
        at org.cactoos.scalar.And.value(And.java:52)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
        ... 3 more
Caused by: java.io.IOException: java.lang.IllegalStateException: javassist.NotFoundException: com.company.releng.tools.deploy.locations.DeployLocations
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
        ... 13 more
Caused by: java.lang.IllegalStateException: javassist.NotFoundException: com.company.releng.tools.deploy.locations.DeployLocations
        at org.jpeek.metrics.cohesion.CAMC.metric(CAMC.java:146)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
        ... 14 more
Caused by: javassist.NotFoundException: com.company.releng.tools.deploy.locations.DeployLocations
        at javassist.ClassPool.get(ClassPool.java:445)
        at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:592)
        at javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:439)
        at javassist.CtBehavior.getParameterTypes(CtBehavior.java:298)
        at org.jpeek.metrics.cohesion.CAMC.methods(CAMC.java:196)
        at org.jpeek.metrics.cohesion.CAMC.cohesion(CAMC.java:157)
        at org.jpeek.metrics.cohesion.CAMC.metric(CAMC.java:142)
        ... 15 more
```

When trying to build the tool from source using `mvn clean package` , the build fails due to errors in tests:
```
# Build tests fail

Tests in error: 
  AppTest.createsXmlReports:50 » IO java.lang.IllegalArgumentException: 40 error...
  MainTest.createsXmlReports:47 » IO java.lang.IllegalArgumentException: 40 erro...

Tests run: 11, Failures: 4, Errors: 2, Skipped: 0
```
Building with `mvn clean package -DskipTests` produces the desired jar.

However when running this file, another exception occurs:
```
~/git/master$ java -jar ~/source/jpeek/target/jpeek-1.0-SNAPSHOT-jar-with-dependencies.jar . /tmp/jpeek
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.io.IOException: java.io.UncheckedIOException: java.io.IOException: javassist.NotFoundException: org.apache.commons.cli.CommandLine
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
        at org.jpeek.App.analyze(App.java:114)
        at org.jpeek.Main.main(Main.java:61)
Caused by: java.io.UncheckedIOException: java.io.IOException: javassist.NotFoundException: org.apache.commons.cli.CommandLine
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
        at org.cactoos.iterator.Mapped.next(Mapped.java:70)
        at org.jpeek.metrics.JavassistClasses.metrics(JavassistClasses.java:129)
        at org.jpeek.metrics.JavassistClasses.xembly(JavassistClasses.java:101)
        at org.jpeek.metrics.cohesion.CAMC.xembly(CAMC.java:76)
        at org.jpeek.App.xml(App.java:134)
        at org.jpeek.App.lambda$analyze$0(App.java:102)
        at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
        at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
        at org.cactoos.scalar.And.lambda$null$0(And.java:101)
        at org.cactoos.scalar.And.value(And.java:127)
        at org.cactoos.scalar.And.value(And.java:52)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
        ... 3 more
Caused by: java.io.IOException: javassist.NotFoundException: org.apache.commons.cli.CommandLine
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
        at org.jpeek.metrics.JavassistClasses.metric(JavassistClasses.java:147)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
        ... 15 more
Caused by: javassist.NotFoundException: org.apache.commons.cli.CommandLine
        at javassist.ClassPool.get(ClassPool.java:445)
        at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:592)
        at javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:439)
        at javassist.CtBehavior.getParameterTypes(CtBehavior.java:298)
        at org.jpeek.metrics.cohesion.CAMC.methods(CAMC.java:139)
        at org.jpeek.metrics.cohesion.CAMC.cohesion(CAMC.java:86)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
        ... 18 more
```
Am I missing something or did I catch the project in an unfortunate state?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@wolkenschieber this is weird... everything works for me. Well, worked yesterday. Let me check now. Thanks for reporting!

**Comment by yegor256** [comment]
@wolkenschieber what is the version of Java and Maven in your computer?

**Comment by wolkenschieber** [comment]
@yegor256 You're very welcome and thanks for this project!

I switched machines. This one runs OpenJDK Runtime Environment (build 1.8.0_144-b01) and Apache Maven 3.5.0.

The source build `jpeek-1.0-SNAPSHOT-jar-with-dependencies.jar` here shows the same behaviour as mentioned in the inital comment.

Playing around I found out that the issue occurs, if there are `class` files in the `bin` directories. As soon as I removed those, the errors were gone.

Now I'm unsure about the results. It feels like I'm using the tool wrong.

**Comment by yegor256** [comment]
@wolkenschieber the bug you see when you run the tool is valid. It breaks on my machine too. I'm worried about you not being able to build the project. Can you please try `mvn clean install` again and post the stacktrace of the error you see?

**Comment by wolkenschieber** [comment]
I've attached the build output to this [gist](https://gist.github.com/wolkenschieber/1be2f1138908b53aad581e1b8903a027).

**Comment by yegor256** [comment]
@wolkenschieber it was a locale problem, fixed in 3f562da Can you please try again?

**Comment by wolkenschieber** [comment]
Pulled the latest source and the project builds fine now.

**Comment by wolkenschieber** [comment]
I'm still unsure about those `javassist.NotFoundException` I'm getting.

To reproduce:
* Clone [RxJava](https://github.com/ReactiveX/RxJava)
* Build RxJava using `./gradlew clean assemble`
* Run jpeek in RxJava root using `java -jar /tmp/jpeek/target/jpeek-1.0-SNAPSHOT-jar-with-dependencies.jar . /tmp/results`
* Following exception occurs: `Exception in thread "main" java.io.IOException: java.io.UncheckedIOException: java.io.IOException: javassist.NotFoundException: org.reactivestreams.Subscription`

**Comment by yegor256** [comment]
@wolkenschieber I believe the problem with running the JAR is fixed too, in 97753b2 Please, try again.

**Comment by wolkenschieber** [comment]
@yegor256 That did it. I'm able to analyse all projects from the previous comment without any error message.

For me it's now homework time: I haven't read the papers yet and many of my classes aren't green. 

Thanks for resolving the issue so quickly!

**Comment by yegor256** [comment]
@wolkenschieber thanks for your patience. please, close the ticket)

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#20`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#20` is not in scope.
