### ISSUE TITLE
Build is broken with java11

### ISSUE THREAD

**Issue by Serranya** [yegor256/jpeek#272]
When trying to build jPeek with
```
[serra@archlinux jpeek]$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13)
OpenJDK 64-Bit Server VM (build 11.0.1+13, mixed mode)
```
and
```
[serra@archlinux jpeek]$ mvn -v
Apache Maven 3.6.0 (NON-CANONICAL_2018-11-06T03:14:22+01:00_root; 2018-11-06T03:14:22+01:00)
Maven home: /opt/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.19.4-arch1-1-arch", arch: "amd64", family: "unix"
```

the build fails with the following error
```
[serra@archlinux jpeek]$ mvn -V clean package -Pqulice
Apache Maven 3.6.0 (NON-CANONICAL_2018-11-06T03:14:22+01:00_root; 2018-11-06T03:14:22+01:00)
Maven home: /opt/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.19.4-arch1-1-arch", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< org.jpeek:jpeek >---------------------------
[INFO] Building jpeek 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ jpeek ---
[INFO] Deleting /home/serra/dev/jpeek/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ jpeek ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (jcabi-build-number) @ jpeek ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd '/home/serra/dev/jpeek' && 'git' 'rev-parse' '--verify' '--short=7' 'HEAD'
[INFO] Working directory: /home/serra/dev/jpeek
[INFO] Storing buildNumber: 48fcf32 at timestamp: 2018-11-29T12:28:34
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (jcabi-build-number) @ jpeek ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent (jacoco-initialize) @ jpeek ---
[INFO] argLine set to -javaagent:/home/serra/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/serra/dev/jpeek/target/jacoco.exec,output=file
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ jpeek ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 45 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ jpeek ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 39 source files to /home/serra/dev/jpeek/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ jpeek ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ jpeek ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /home/serra/dev/jpeek/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ jpeek ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_e5875b2.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_e5875b2.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_e5875b2.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_e5875b2.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
FATAL ERROR in native method: processing of -javaagent failed
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_e5875b2.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.853 s
[INFO] Finished at: 2018-11-29T12:28:43+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jpeek: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/serra/dev/jpeek && /usr/lib/jvm/java-11-openjdk/bin/java -javaagent:/home/serra/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/serra/dev/jpeek/target/jacoco.exec,output=file -jar /home/serra/dev/jpeek/target/surefire/surefirebooter8963383785093540675.jar /home/serra/dev/jpeek/target/surefire/surefire10945831819619068553tmp /home/serra/dev/jpeek/target/surefire/surefire_012785763846386970724tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

We should make sure that we stay compatible with more recent java releases.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by Protagores** [comment]
Would need to update, in `pom.xml`, the versions of following dependencies:
- org.jacoco:jacoco-maven-plugin
- org.ow2.asm:asm

Also impeded by teamed/qulice#878

**Comment by mohamednizar** [comment]
@Protagores can't add a permanent fix for java 11 or latest? @paulodamaso we need a permanent solution for this.

**Comment by Protagores** [comment]
@mohamednizar Dependency version update is trivial, in fact I am going to do this in my next pull request.

However the `mvn -Pqulice` option might still not be working though. Somehow it currently works for me with OpenJDK 11, so I can’t reproduce the issue I referenced above at this point.
