### ISSUE TITLE
content-type is static

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#31]
Let's make it smarter

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#31` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.1`

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4535](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4535](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: event of type 'closed' not found in issue #31
	at com.jcabi.github.Issue$Smart.latestEvent_aroundBody40(Issue.java:365)
	at com.jcabi.github.Issue$Smart$AjcClosure41.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.latestEvent(Issue.java:354)
	at com.zerocracy.radars.github.RbVerifyCloser.closer(RbVerifyCloser.java:83)
	at com.zerocracy.radars.github.RbVerifyCloser.react(RbVerifyCloser.java:47)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Re...
```

My version: `1.0-SNAPSHOT`, `8836b42`, `2017-10-26T18:36:31` /cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#31` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4605](http://www.0crat.com/u/yegor256).
