### ISSUE TITLE
summary report by classes

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#35]
Let's make a summary by classes.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 8836b42 2017-10-26T18:36:31
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/penalize_for_manual_assignment.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/penalize_for_manual_assignment.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.brigade.StkWithStatus.process(StkWithStatus.java:55)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:101)
	at com.zerocracy.farm.reactive.Brigade.lambda$process$0(Brigade.java:83)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.value(LengthOf.java:56)
	at org.cactoos.iterable.LengthOf.value(LengthOf.java:56)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:85)
	at com.zerocracy.farm.reactive.Flush.process(Flush.java:86)
	at com.zerocracy.farm.reactive.Flush.exec(Flush.java:71)
	at com.zerocr...
```

Cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#35` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4625](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4625](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.8`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#35` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4655](http://www.0crat.com/u/yegor256).
