### ISSUE TITLE
Test org.jpeek.web.ReportsTest#rendersOneReport is unstable

### ISSUE THREAD

**Issue by akryvtsun** [yegor256/jpeek#368]
The test execution is unstable and probable depends on environment state.

1. The test is failed on local environment
```
java.io.IOException: Cannot run program "unzip" (in directory "C:\Users\AKRYVT~1\AppData\Local\Temp\x4718881456374315808\sources\com\jcabi\jcabi-urn"): CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at org.jpeek.web.Reports.apply(Reports.java:132)
        at org.jpeek.web.Reports.apply(Reports.java:55)
        at org.jpeek.web.ReportsTest.rendersOneReport(ReportsTest.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 23 more
``` 
2. The test is broken on Trevis  env. as part of #366 PR
https://travis-ci.org/yegor256/jpeek/builds/632328904#L1574
with exception
```
java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo1.maven.org/maven2/com/jcabi/jcabi-urn/maven-metadata.xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at org.cactoos.io.InputOf.lambda$new$4(InputOf.java:103)
	at org.cactoos.io.InputOf.stream(InputOf.java:310)
	at org.cactoos.io.TeeInput.stream(TeeInput.java:867)
	at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:77)
	at org.cactoos.io.BytesOf.asBytes(BytesOf.java:341)
	at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:297)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:65)
	at org.jpeek.web.Reports.apply(Reports.java:102)
	at org.jpeek.web.Reports.apply(Reports.java:55)
	at org.jpeek.web.ReportsTest.rendersOneReport(ReportsTest.java:83)
        ...
```
_I would like to have the test stable._ If environment really doesn't have smth is needed for test execution, probable, we should make this test as ignored.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/368#issuecomment-573695580))

@paulodamaso Job [#368](https://github.com/yegor256/jpeek/issues/368) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @akryvtsun[/z](https://www.0crat.com/u/akryvtsun)

**Comment by 0crat** [comment]
The job [#368](https://github.com/yegor256/jpeek/issues/368) assigned to @monomonedula[/z](https://www.0crat.com/u/monomonedula), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/dfd98981-e992-438d-b28c-64ad300a50ef); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@monomonedula[/z](https://www.0crat.com/u/monomonedula) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @monomonedula[/z](https://www.0crat.com/u/monomonedula) resigned from [#368](https://github.com/yegor256/jpeek/issues/368), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @monomonedula[/z](https://www.0crat.com/u/monomonedula)

**Comment by 0crat** [comment]
The job [#368](https://github.com/yegor256/jpeek/issues/368) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/a671585a-6c15-460c-a539-63eeb0e65a32); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by dgarus** [comment]
> @dgarus[/z](https://www.0crat.com/u/dgarus) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

@paulodamaso Hi!
Why this job will be taken away from me?
I've prepared the PR 6 days ago.

**Comment by paulodamaso** [comment]
@dgarus We have a 10 day limit to close issues, as per the policy ([here](https://www.zerocracy.com/policy.html#8)). As you have already made the PR and are waiting for the review, I suggest you to add an impediment to this (see [here](https://www.zerocracy.com/policy.html#9))

**Comment by dgarus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/368#issuecomment-591937420))

@dgarus The impediment for [#368](https://github.com/yegor256/jpeek/issues/368) was registered successfully by @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by dgarus** [comment]
@akryvtsun could you pls close the issue?

**Comment by paulodamaso** [comment]
@dgarus Thank you!
