### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#37]
```
java.io.IOException: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:74)
	at org.jpeek.web.TkReport.act(TkReport.java:74)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:209)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.jpeek.web.AsyncReports.apply(AsyncReports.java:86)
	at org.jpeek.web.AsyncReports.apply(AsyncReports.java:54)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	... 15 more
Caused by: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jpeek.web.AsyncReports.apply(AsyncReports.java:84)
	... 17 more
Caused by: java.io.UncheckedIOException: java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:61)
	at org.cactoos.iterator.Mapped.next(Mapped.java:70)
	at org.cactoos.iterable.Joined.iterator(Joined.java:68)
	at org.cactoos.collection.Joined.iterator(Joined.java:97)
	at org.xembly.Directives.append(Directives.java:250)
	at org.jpeek.Index.value(Index.java:72)
	at org.jpeek.App.analyze(App.java:135)
	at org.jpeek.web.Reports.apply(Reports.java:136)
	at org.jpeek.web.Reports.apply(Reports.java:49)
	at org.jpeek.web.Futures.lambda$apply$0(Futures.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	... 1 more
Caused by: java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	... 14 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at org.cactoos.list.Sorted.get(Sorted.java:185)
	at org.jpeek.Index.metric(Index.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	... 15 more
```

**Comment by yegor256** [comment]
Here: http://i.jpeek.org/org.springframework.boot/spring-boot-starter-web/index.html

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#37` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4755](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4755](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#37` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4835](http://www.0crat.com/u/yegor256).
