### ISSUE TITLE
running out of memory

### ISSUE THREAD

**Issue by yegor256** [yegor256/jpeek#56]
Heroku logs:

```
2017-11-06T15:16:08.710384+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:16:31.142395+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:16:31.142499+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:16:52.583138+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:16:52.583189+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:17:14.414977+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:17:14.415136+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:17:36.968745+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:17:36.968940+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:17:59.260627+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:17:59.260845+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:18:20.801884+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:18:20.801884+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:18:42.533605+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:18:42.533660+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:19:05.481493+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:19:05.481529+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-06T15:19:27.573072+00:00 heroku[web.1]: Process running mem=594M(109.6%)
2017-11-06T15:19:27.573248+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

We seem to be leaking memory resources somewhere. Let's investigate and fix.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com...
```

My version: `1.0-SNAPSHOT`, `4fbcb81`, `2017-10-30T15:19:50` /cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#56` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+5190](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jpeek#56` is already in scope.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jpeek#56`.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#56` is now out of scope.
